title: Python Course 2022/2023
author: Alexander Ignatov, Lyuboslav Karev, Ivan Luchev
logo: misc/logo.png

execute:
  execute_notebooks: off
  
repository:
  url: https://github.com/fmipython/PythonCourse2022
  branch: main

html:
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true

launch_buttons:
  colab_url: "https://colab.research.google.com"
